// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/android.dart';
import 'api/java_download.dart';
import 'api/jre_scan.dart';
import 'api/launcher.dart';
import 'api/mcim_fallback_api.dart';
import 'api/project_i18n.dart';
import 'api/simple.dart';
import 'api/storage_scan.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(bool, String?)
      dco_decode_DartFn_Inputs_bool_opt_String_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  FutureOr<void> Function(double, String)
      dco_decode_DartFn_Inputs_f_64_String_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  FutureOr<void> Function(LiveLogEventDto)
      dco_decode_DartFn_Inputs_live_log_event_dto_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  FutureOr<void> Function(ProcessEventDto)
      dco_decode_DartFn_Inputs_process_event_dto_Output_unit_AnyhowException(
          dynamic raw);

  @protected
  FutureOr<bool> Function(WorldMapStreamEventDto)
      dco_decode_DartFn_Inputs_world_map_stream_event_dto_Output_bool_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountDto dco_decode_account_dto(dynamic raw);

  @protected
  AssetPreviewCatalogDto dco_decode_asset_preview_catalog_dto(dynamic raw);

  @protected
  AssetPreviewEntryDto dco_decode_asset_preview_entry_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountDto dco_decode_box_autoadd_account_dto(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  JavaRuntimeVersion dco_decode_box_autoadd_java_runtime_version(dynamic raw);

  @protected
  ModelFaceDto dco_decode_box_autoadd_model_face_dto(dynamic raw);

  @protected
  StagedJreDto dco_decode_box_autoadd_staged_jre_dto(dynamic raw);

  @protected
  TextI18nDto dco_decode_box_autoadd_text_i_18_n_dto(dynamic raw);

  @protected
  TranslationCacheStatsDto dco_decode_box_autoadd_translation_cache_stats_dto(
      dynamic raw);

  @protected
  WorldMapChunkDto dco_decode_box_autoadd_world_map_chunk_dto(dynamic raw);

  @protected
  CapeDto dco_decode_cape_dto(dynamic raw);

  @protected
  DeviceCodeLoginBeginDto dco_decode_device_code_login_begin_dto(dynamic raw);

  @protected
  DeviceCodePollResultDto dco_decode_device_code_poll_result_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GameVersionDto dco_decode_game_version_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InstanceDto dco_decode_instance_dto(dynamic raw);

  @protected
  InstanceMeasureResult dco_decode_instance_measure_result(dynamic raw);

  @protected
  InstancePartStat dco_decode_instance_part_stat(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  JavaRuntimeVersion dco_decode_java_runtime_version(dynamic raw);

  @protected
  LaunchDefaultsDto dco_decode_launch_defaults_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountDto> dco_decode_list_account_dto(dynamic raw);

  @protected
  List<AssetPreviewEntryDto> dco_decode_list_asset_preview_entry_dto(
      dynamic raw);

  @protected
  List<CapeDto> dco_decode_list_cape_dto(dynamic raw);

  @protected
  List<GameVersionDto> dco_decode_list_game_version_dto(dynamic raw);

  @protected
  List<InstanceDto> dco_decode_list_instance_dto(dynamic raw);

  @protected
  List<InstanceMeasureResult> dco_decode_list_instance_measure_result(
      dynamic raw);

  @protected
  List<InstancePartStat> dco_decode_list_instance_part_stat(dynamic raw);

  @protected
  List<JavaRuntimeVersion> dco_decode_list_java_runtime_version(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<LoaderVersionDto> dco_decode_list_loader_version_dto(dynamic raw);

  @protected
  List<LocalizeProjectInputDto> dco_decode_list_localize_project_input_dto(
      dynamic raw);

  @protected
  List<LocalizedProjectDto> dco_decode_list_localized_project_dto(dynamic raw);

  @protected
  List<ModFileDto> dco_decode_list_mod_file_dto(dynamic raw);

  @protected
  List<ModelElementDto> dco_decode_list_model_element_dto(dynamic raw);

  @protected
  List<PackContentCategoryDto> dco_decode_list_pack_content_category_dto(
      dynamic raw);

  @protected
  List<PackContentFileDto> dco_decode_list_pack_content_file_dto(dynamic raw);

  @protected
  List<PathMeasureRequest> dco_decode_list_path_measure_request(dynamic raw);

  @protected
  List<PathMeasureResult> dco_decode_list_path_measure_result(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProcessDto> dco_decode_list_process_dto(dynamic raw);

  @protected
  List<ProjectI18nDto> dco_decode_list_project_i_18_n_dto(dynamic raw);

  @protected
  List<ProjectI18nKeyDto> dco_decode_list_project_i_18_n_key_dto(dynamic raw);

  @protected
  List<ProjectI18nUpsertDto> dco_decode_list_project_i_18_n_upsert_dto(
      dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SkinDto> dco_decode_list_skin_dto(dynamic raw);

  @protected
  List<WorldBackupDto> dco_decode_list_world_backup_dto(dynamic raw);

  @protected
  List<WorldDto> dco_decode_list_world_dto(dynamic raw);

  @protected
  List<YggdrasilProfileDto> dco_decode_list_yggdrasil_profile_dto(dynamic raw);

  @protected
  List<YggdrasilServiceDto> dco_decode_list_yggdrasil_service_dto(dynamic raw);

  @protected
  LiveLogEventDto dco_decode_live_log_event_dto(dynamic raw);

  @protected
  LoaderVersionDto dco_decode_loader_version_dto(dynamic raw);

  @protected
  LocalizeProjectInputDto dco_decode_localize_project_input_dto(dynamic raw);

  @protected
  LocalizedProjectDto dco_decode_localized_project_dto(dynamic raw);

  @protected
  McimHttpResponse dco_decode_mcim_http_response(dynamic raw);

  @protected
  ModFileDto dco_decode_mod_file_dto(dynamic raw);

  @protected
  ModelElementDto dco_decode_model_element_dto(dynamic raw);

  @protected
  ModelFaceDto dco_decode_model_face_dto(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AccountDto? dco_decode_opt_box_autoadd_account_dto(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  JavaRuntimeVersion? dco_decode_opt_box_autoadd_java_runtime_version(
      dynamic raw);

  @protected
  ModelFaceDto? dco_decode_opt_box_autoadd_model_face_dto(dynamic raw);

  @protected
  StagedJreDto? dco_decode_opt_box_autoadd_staged_jre_dto(dynamic raw);

  @protected
  TextI18nDto? dco_decode_opt_box_autoadd_text_i_18_n_dto(dynamic raw);

  @protected
  WorldMapChunkDto? dco_decode_opt_box_autoadd_world_map_chunk_dto(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PackContentCategoryDto dco_decode_pack_content_category_dto(dynamic raw);

  @protected
  PackContentFileDto dco_decode_pack_content_file_dto(dynamic raw);

  @protected
  PackExportPreviewDto dco_decode_pack_export_preview_dto(dynamic raw);

  @protected
  PackImportPreviewDto dco_decode_pack_import_preview_dto(dynamic raw);

  @protected
  PathMeasureRequest dco_decode_path_measure_request(dynamic raw);

  @protected
  PathMeasureResult dco_decode_path_measure_result(dynamic raw);

  @protected
  ProcessDto dco_decode_process_dto(dynamic raw);

  @protected
  ProcessEventDto dco_decode_process_event_dto(dynamic raw);

  @protected
  ProjectI18nDto dco_decode_project_i_18_n_dto(dynamic raw);

  @protected
  ProjectI18nKeyDto dco_decode_project_i_18_n_key_dto(dynamic raw);

  @protected
  ProjectI18nUpsertDto dco_decode_project_i_18_n_upsert_dto(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  ResolvedAssetPreviewDto dco_decode_resolved_asset_preview_dto(dynamic raw);

  @protected
  ServerStatusDto dco_decode_server_status_dto(dynamic raw);

  @protected
  SkinDto dco_decode_skin_dto(dynamic raw);

  @protected
  StagedJreDto dco_decode_staged_jre_dto(dynamic raw);

  @protected
  TextI18nDto dco_decode_text_i_18_n_dto(dynamic raw);

  @protected
  TranslationCacheStatsDto dco_decode_translation_cache_stats_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WorldBackupDto dco_decode_world_backup_dto(dynamic raw);

  @protected
  WorldDto dco_decode_world_dto(dynamic raw);

  @protected
  WorldMapChunkDto dco_decode_world_map_chunk_dto(dynamic raw);

  @protected
  WorldMapStreamEventDto dco_decode_world_map_stream_event_dto(dynamic raw);

  @protected
  YggdrasilLoginBeginDto dco_decode_yggdrasil_login_begin_dto(dynamic raw);

  @protected
  YggdrasilProfileDto dco_decode_yggdrasil_profile_dto(dynamic raw);

  @protected
  YggdrasilServiceDto dco_decode_yggdrasil_service_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer);

  @protected
  AssetPreviewCatalogDto sse_decode_asset_preview_catalog_dto(
      SseDeserializer deserializer);

  @protected
  AssetPreviewEntryDto sse_decode_asset_preview_entry_dto(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_box_autoadd_account_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JavaRuntimeVersion sse_decode_box_autoadd_java_runtime_version(
      SseDeserializer deserializer);

  @protected
  ModelFaceDto sse_decode_box_autoadd_model_face_dto(
      SseDeserializer deserializer);

  @protected
  StagedJreDto sse_decode_box_autoadd_staged_jre_dto(
      SseDeserializer deserializer);

  @protected
  TextI18nDto sse_decode_box_autoadd_text_i_18_n_dto(
      SseDeserializer deserializer);

  @protected
  TranslationCacheStatsDto sse_decode_box_autoadd_translation_cache_stats_dto(
      SseDeserializer deserializer);

  @protected
  WorldMapChunkDto sse_decode_box_autoadd_world_map_chunk_dto(
      SseDeserializer deserializer);

  @protected
  CapeDto sse_decode_cape_dto(SseDeserializer deserializer);

  @protected
  DeviceCodeLoginBeginDto sse_decode_device_code_login_begin_dto(
      SseDeserializer deserializer);

  @protected
  DeviceCodePollResultDto sse_decode_device_code_poll_result_dto(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GameVersionDto sse_decode_game_version_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InstanceDto sse_decode_instance_dto(SseDeserializer deserializer);

  @protected
  InstanceMeasureResult sse_decode_instance_measure_result(
      SseDeserializer deserializer);

  @protected
  InstancePartStat sse_decode_instance_part_stat(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  JavaRuntimeVersion sse_decode_java_runtime_version(
      SseDeserializer deserializer);

  @protected
  LaunchDefaultsDto sse_decode_launch_defaults_dto(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountDto> sse_decode_list_account_dto(SseDeserializer deserializer);

  @protected
  List<AssetPreviewEntryDto> sse_decode_list_asset_preview_entry_dto(
      SseDeserializer deserializer);

  @protected
  List<CapeDto> sse_decode_list_cape_dto(SseDeserializer deserializer);

  @protected
  List<GameVersionDto> sse_decode_list_game_version_dto(
      SseDeserializer deserializer);

  @protected
  List<InstanceDto> sse_decode_list_instance_dto(SseDeserializer deserializer);

  @protected
  List<InstanceMeasureResult> sse_decode_list_instance_measure_result(
      SseDeserializer deserializer);

  @protected
  List<InstancePartStat> sse_decode_list_instance_part_stat(
      SseDeserializer deserializer);

  @protected
  List<JavaRuntimeVersion> sse_decode_list_java_runtime_version(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<LoaderVersionDto> sse_decode_list_loader_version_dto(
      SseDeserializer deserializer);

  @protected
  List<LocalizeProjectInputDto> sse_decode_list_localize_project_input_dto(
      SseDeserializer deserializer);

  @protected
  List<LocalizedProjectDto> sse_decode_list_localized_project_dto(
      SseDeserializer deserializer);

  @protected
  List<ModFileDto> sse_decode_list_mod_file_dto(SseDeserializer deserializer);

  @protected
  List<ModelElementDto> sse_decode_list_model_element_dto(
      SseDeserializer deserializer);

  @protected
  List<PackContentCategoryDto> sse_decode_list_pack_content_category_dto(
      SseDeserializer deserializer);

  @protected
  List<PackContentFileDto> sse_decode_list_pack_content_file_dto(
      SseDeserializer deserializer);

  @protected
  List<PathMeasureRequest> sse_decode_list_path_measure_request(
      SseDeserializer deserializer);

  @protected
  List<PathMeasureResult> sse_decode_list_path_measure_result(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProcessDto> sse_decode_list_process_dto(SseDeserializer deserializer);

  @protected
  List<ProjectI18nDto> sse_decode_list_project_i_18_n_dto(
      SseDeserializer deserializer);

  @protected
  List<ProjectI18nKeyDto> sse_decode_list_project_i_18_n_key_dto(
      SseDeserializer deserializer);

  @protected
  List<ProjectI18nUpsertDto> sse_decode_list_project_i_18_n_upsert_dto(
      SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<SkinDto> sse_decode_list_skin_dto(SseDeserializer deserializer);

  @protected
  List<WorldBackupDto> sse_decode_list_world_backup_dto(
      SseDeserializer deserializer);

  @protected
  List<WorldDto> sse_decode_list_world_dto(SseDeserializer deserializer);

  @protected
  List<YggdrasilProfileDto> sse_decode_list_yggdrasil_profile_dto(
      SseDeserializer deserializer);

  @protected
  List<YggdrasilServiceDto> sse_decode_list_yggdrasil_service_dto(
      SseDeserializer deserializer);

  @protected
  LiveLogEventDto sse_decode_live_log_event_dto(SseDeserializer deserializer);

  @protected
  LoaderVersionDto sse_decode_loader_version_dto(SseDeserializer deserializer);

  @protected
  LocalizeProjectInputDto sse_decode_localize_project_input_dto(
      SseDeserializer deserializer);

  @protected
  LocalizedProjectDto sse_decode_localized_project_dto(
      SseDeserializer deserializer);

  @protected
  McimHttpResponse sse_decode_mcim_http_response(SseDeserializer deserializer);

  @protected
  ModFileDto sse_decode_mod_file_dto(SseDeserializer deserializer);

  @protected
  ModelElementDto sse_decode_model_element_dto(SseDeserializer deserializer);

  @protected
  ModelFaceDto sse_decode_model_face_dto(SseDeserializer deserializer);

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AccountDto? sse_decode_opt_box_autoadd_account_dto(
      SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JavaRuntimeVersion? sse_decode_opt_box_autoadd_java_runtime_version(
      SseDeserializer deserializer);

  @protected
  ModelFaceDto? sse_decode_opt_box_autoadd_model_face_dto(
      SseDeserializer deserializer);

  @protected
  StagedJreDto? sse_decode_opt_box_autoadd_staged_jre_dto(
      SseDeserializer deserializer);

  @protected
  TextI18nDto? sse_decode_opt_box_autoadd_text_i_18_n_dto(
      SseDeserializer deserializer);

  @protected
  WorldMapChunkDto? sse_decode_opt_box_autoadd_world_map_chunk_dto(
      SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PackContentCategoryDto sse_decode_pack_content_category_dto(
      SseDeserializer deserializer);

  @protected
  PackContentFileDto sse_decode_pack_content_file_dto(
      SseDeserializer deserializer);

  @protected
  PackExportPreviewDto sse_decode_pack_export_preview_dto(
      SseDeserializer deserializer);

  @protected
  PackImportPreviewDto sse_decode_pack_import_preview_dto(
      SseDeserializer deserializer);

  @protected
  PathMeasureRequest sse_decode_path_measure_request(
      SseDeserializer deserializer);

  @protected
  PathMeasureResult sse_decode_path_measure_result(
      SseDeserializer deserializer);

  @protected
  ProcessDto sse_decode_process_dto(SseDeserializer deserializer);

  @protected
  ProcessEventDto sse_decode_process_event_dto(SseDeserializer deserializer);

  @protected
  ProjectI18nDto sse_decode_project_i_18_n_dto(SseDeserializer deserializer);

  @protected
  ProjectI18nKeyDto sse_decode_project_i_18_n_key_dto(
      SseDeserializer deserializer);

  @protected
  ProjectI18nUpsertDto sse_decode_project_i_18_n_upsert_dto(
      SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  ResolvedAssetPreviewDto sse_decode_resolved_asset_preview_dto(
      SseDeserializer deserializer);

  @protected
  ServerStatusDto sse_decode_server_status_dto(SseDeserializer deserializer);

  @protected
  SkinDto sse_decode_skin_dto(SseDeserializer deserializer);

  @protected
  StagedJreDto sse_decode_staged_jre_dto(SseDeserializer deserializer);

  @protected
  TextI18nDto sse_decode_text_i_18_n_dto(SseDeserializer deserializer);

  @protected
  TranslationCacheStatsDto sse_decode_translation_cache_stats_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WorldBackupDto sse_decode_world_backup_dto(SseDeserializer deserializer);

  @protected
  WorldDto sse_decode_world_dto(SseDeserializer deserializer);

  @protected
  WorldMapChunkDto sse_decode_world_map_chunk_dto(SseDeserializer deserializer);

  @protected
  WorldMapStreamEventDto sse_decode_world_map_stream_event_dto(
      SseDeserializer deserializer);

  @protected
  YggdrasilLoginBeginDto sse_decode_yggdrasil_login_begin_dto(
      SseDeserializer deserializer);

  @protected
  YggdrasilProfileDto sse_decode_yggdrasil_profile_dto(
      SseDeserializer deserializer);

  @protected
  YggdrasilServiceDto sse_decode_yggdrasil_service_dto(
      SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_bool_opt_String_Output_unit_AnyhowException(
      FutureOr<void> Function(bool, String?) self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_f_64_String_Output_unit_AnyhowException(
      FutureOr<void> Function(double, String) self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_live_log_event_dto_Output_unit_AnyhowException(
      FutureOr<void> Function(LiveLogEventDto) self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_process_event_dto_Output_unit_AnyhowException(
      FutureOr<void> Function(ProcessEventDto) self, SseSerializer serializer);

  @protected
  void
      sse_encode_DartFn_Inputs_world_map_stream_event_dto_Output_bool_AnyhowException(
          FutureOr<bool> Function(WorldMapStreamEventDto) self,
          SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_asset_preview_catalog_dto(
      AssetPreviewCatalogDto self, SseSerializer serializer);

  @protected
  void sse_encode_asset_preview_entry_dto(
      AssetPreviewEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_dto(
      AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_java_runtime_version(
      JavaRuntimeVersion self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_model_face_dto(
      ModelFaceDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_staged_jre_dto(
      StagedJreDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_text_i_18_n_dto(
      TextI18nDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_translation_cache_stats_dto(
      TranslationCacheStatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_world_map_chunk_dto(
      WorldMapChunkDto self, SseSerializer serializer);

  @protected
  void sse_encode_cape_dto(CapeDto self, SseSerializer serializer);

  @protected
  void sse_encode_device_code_login_begin_dto(
      DeviceCodeLoginBeginDto self, SseSerializer serializer);

  @protected
  void sse_encode_device_code_poll_result_dto(
      DeviceCodePollResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_game_version_dto(
      GameVersionDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_instance_dto(InstanceDto self, SseSerializer serializer);

  @protected
  void sse_encode_instance_measure_result(
      InstanceMeasureResult self, SseSerializer serializer);

  @protected
  void sse_encode_instance_part_stat(
      InstancePartStat self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_java_runtime_version(
      JavaRuntimeVersion self, SseSerializer serializer);

  @protected
  void sse_encode_launch_defaults_dto(
      LaunchDefaultsDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_dto(
      List<AccountDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_asset_preview_entry_dto(
      List<AssetPreviewEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cape_dto(List<CapeDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_game_version_dto(
      List<GameVersionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_instance_dto(
      List<InstanceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_instance_measure_result(
      List<InstanceMeasureResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_instance_part_stat(
      List<InstancePartStat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_java_runtime_version(
      List<JavaRuntimeVersion> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_loader_version_dto(
      List<LoaderVersionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_localize_project_input_dto(
      List<LocalizeProjectInputDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_localized_project_dto(
      List<LocalizedProjectDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mod_file_dto(
      List<ModFileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_model_element_dto(
      List<ModelElementDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pack_content_category_dto(
      List<PackContentCategoryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pack_content_file_dto(
      List<PackContentFileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_path_measure_request(
      List<PathMeasureRequest> self, SseSerializer serializer);

  @protected
  void sse_encode_list_path_measure_result(
      List<PathMeasureResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_dto(
      List<ProcessDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_project_i_18_n_dto(
      List<ProjectI18nDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_project_i_18_n_key_dto(
      List<ProjectI18nKeyDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_project_i_18_n_upsert_dto(
      List<ProjectI18nUpsertDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_skin_dto(List<SkinDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_world_backup_dto(
      List<WorldBackupDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_world_dto(List<WorldDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_yggdrasil_profile_dto(
      List<YggdrasilProfileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_yggdrasil_service_dto(
      List<YggdrasilServiceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_live_log_event_dto(
      LiveLogEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_loader_version_dto(
      LoaderVersionDto self, SseSerializer serializer);

  @protected
  void sse_encode_localize_project_input_dto(
      LocalizeProjectInputDto self, SseSerializer serializer);

  @protected
  void sse_encode_localized_project_dto(
      LocalizedProjectDto self, SseSerializer serializer);

  @protected
  void sse_encode_mcim_http_response(
      McimHttpResponse self, SseSerializer serializer);

  @protected
  void sse_encode_mod_file_dto(ModFileDto self, SseSerializer serializer);

  @protected
  void sse_encode_model_element_dto(
      ModelElementDto self, SseSerializer serializer);

  @protected
  void sse_encode_model_face_dto(ModelFaceDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_String_None(
      Map<String, String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_account_dto(
      AccountDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_java_runtime_version(
      JavaRuntimeVersion? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_model_face_dto(
      ModelFaceDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_staged_jre_dto(
      StagedJreDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_text_i_18_n_dto(
      TextI18nDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_world_map_chunk_dto(
      WorldMapChunkDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_pack_content_category_dto(
      PackContentCategoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_pack_content_file_dto(
      PackContentFileDto self, SseSerializer serializer);

  @protected
  void sse_encode_pack_export_preview_dto(
      PackExportPreviewDto self, SseSerializer serializer);

  @protected
  void sse_encode_pack_import_preview_dto(
      PackImportPreviewDto self, SseSerializer serializer);

  @protected
  void sse_encode_path_measure_request(
      PathMeasureRequest self, SseSerializer serializer);

  @protected
  void sse_encode_path_measure_result(
      PathMeasureResult self, SseSerializer serializer);

  @protected
  void sse_encode_process_dto(ProcessDto self, SseSerializer serializer);

  @protected
  void sse_encode_process_event_dto(
      ProcessEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_project_i_18_n_dto(
      ProjectI18nDto self, SseSerializer serializer);

  @protected
  void sse_encode_project_i_18_n_key_dto(
      ProjectI18nKeyDto self, SseSerializer serializer);

  @protected
  void sse_encode_project_i_18_n_upsert_dto(
      ProjectI18nUpsertDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_resolved_asset_preview_dto(
      ResolvedAssetPreviewDto self, SseSerializer serializer);

  @protected
  void sse_encode_server_status_dto(
      ServerStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_skin_dto(SkinDto self, SseSerializer serializer);

  @protected
  void sse_encode_staged_jre_dto(StagedJreDto self, SseSerializer serializer);

  @protected
  void sse_encode_text_i_18_n_dto(TextI18nDto self, SseSerializer serializer);

  @protected
  void sse_encode_translation_cache_stats_dto(
      TranslationCacheStatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_world_backup_dto(
      WorldBackupDto self, SseSerializer serializer);

  @protected
  void sse_encode_world_dto(WorldDto self, SseSerializer serializer);

  @protected
  void sse_encode_world_map_chunk_dto(
      WorldMapChunkDto self, SseSerializer serializer);

  @protected
  void sse_encode_world_map_stream_event_dto(
      WorldMapStreamEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_yggdrasil_login_begin_dto(
      YggdrasilLoginBeginDto self, SseSerializer serializer);

  @protected
  void sse_encode_yggdrasil_profile_dto(
      YggdrasilProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_yggdrasil_service_dto(
      YggdrasilServiceDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
