// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Probe the JRE staged at `<files_dir>/jre` without executing it. Returns
/// `None` when no valid JRE is present.
Future<StagedJreDto?> probeStagedJre({required String filesDir}) =>
    RustLib.instance.api.crateApiAndroidProbeStagedJre(filesDir: filesDir);

/// Read-only information about a JRE staged in the app files dir.
class StagedJreDto {
  /// Absolute JRE root path.
  final String javaHome;

  /// Raw version string from the JRE `release` file.
  final String version;

  /// Resolved major version (e.g. 17).
  final int majorVersion;

  /// Target architecture (e.g. "amd64").
  final String arch;

  const StagedJreDto({
    required this.javaHome,
    required this.version,
    required this.majorVersion,
    required this.arch,
  });

  @override
  int get hashCode =>
      javaHome.hashCode ^
      version.hashCode ^
      majorVersion.hashCode ^
      arch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StagedJreDto &&
          runtimeType == other.runtimeType &&
          javaHome == other.javaHome &&
          version == other.version &&
          majorVersion == other.majorVersion &&
          arch == other.arch;
}
