// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `element_to_dto`, `empty`, `face_to_dto`, `map_category`, `map_file`, `mod_file_from_entry`, `progress_cb`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Initialize launcher DB and directory layout under resource_dir.
Future<void> initLauncher({required String resourceDir}) =>
    RustLib.instance.api.crateApiLauncherInitLauncher(resourceDir: resourceDir);

Future<List<InstanceDto>> listInstances() =>
    RustLib.instance.api.crateApiLauncherListInstances();

Future<InstanceDto> getInstance({required String id}) =>
    RustLib.instance.api.crateApiLauncherGetInstance(id: id);

Future<InstanceDto> createInstance(
        {required String name,
        required String gameVersion,
        required String loader,
        String? loaderVersion,
        String? icon}) =>
    RustLib.instance.api.crateApiLauncherCreateInstance(
        name: name,
        gameVersion: gameVersion,
        loader: loader,
        loaderVersion: loaderVersion,
        icon: icon);

Future<InstanceDto> updateInstance(
        {required String id,
        String? name,
        String? javaPath,
        required bool clearJavaPath,
        PlatformInt64? memoryMb,
        required bool clearMemoryMb,
        String? extraJvmArgs,
        required bool clearExtraJvmArgs,
        PlatformInt64? windowWidth,
        PlatformInt64? windowHeight,
        bool? fullscreen,
        required bool clearWindowSettings,
        String? environmentVars,
        required bool clearEnvironmentVars,
        String? preLaunchCommand,
        String? wrapperCommand,
        String? postExitCommand,
        required bool clearHooks,
        String? updateChannel}) =>
    RustLib.instance.api.crateApiLauncherUpdateInstance(
        id: id,
        name: name,
        javaPath: javaPath,
        clearJavaPath: clearJavaPath,
        memoryMb: memoryMb,
        clearMemoryMb: clearMemoryMb,
        extraJvmArgs: extraJvmArgs,
        clearExtraJvmArgs: clearExtraJvmArgs,
        windowWidth: windowWidth,
        windowHeight: windowHeight,
        fullscreen: fullscreen,
        clearWindowSettings: clearWindowSettings,
        environmentVars: environmentVars,
        clearEnvironmentVars: clearEnvironmentVars,
        preLaunchCommand: preLaunchCommand,
        wrapperCommand: wrapperCommand,
        postExitCommand: postExitCommand,
        clearHooks: clearHooks,
        updateChannel: updateChannel);

Future<InstanceDto> setInstanceGroups(
        {required String id, required List<String> groups}) =>
    RustLib.instance.api
        .crateApiLauncherSetInstanceGroups(id: id, groups: groups);

Future<List<String>> listAllInstanceGroups() =>
    RustLib.instance.api.crateApiLauncherListAllInstanceGroups();

Future<LaunchDefaultsDto> getLaunchDefaults() =>
    RustLib.instance.api.crateApiLauncherGetLaunchDefaults();

Future<LaunchDefaultsDto> setLaunchDefaults(
        {required PlatformInt64 memoryMb,
        String? extraJvmArgs,
        required PlatformInt64 windowWidth,
        required PlatformInt64 windowHeight,
        required bool fullscreen,
        String? environmentVars,
        String? preLaunchCommand,
        String? wrapperCommand,
        String? postExitCommand,
        String? gameLanguage}) =>
    RustLib.instance.api.crateApiLauncherSetLaunchDefaults(
        memoryMb: memoryMb,
        extraJvmArgs: extraJvmArgs,
        windowWidth: windowWidth,
        windowHeight: windowHeight,
        fullscreen: fullscreen,
        environmentVars: environmentVars,
        preLaunchCommand: preLaunchCommand,
        wrapperCommand: wrapperCommand,
        postExitCommand: postExitCommand,
        gameLanguage: gameLanguage);

Future<InstanceDto> unlinkModpack({required String id}) =>
    RustLib.instance.api.crateApiLauncherUnlinkModpack(id: id);

Future<InstanceDto> reinstallModpack(
        {required String id,
        String? versionId,
        String? javaPath,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherReinstallModpack(
        id: id,
        versionId: versionId,
        javaPath: javaPath,
        onProgress: onProgress);

/// Set or clear instance icon (local path, URL, or `None` to remove).
Future<InstanceDto> editInstanceIcon({required String id, String? iconPath}) =>
    RustLib.instance.api
        .crateApiLauncherEditInstanceIcon(id: id, iconPath: iconPath);

Future<InstanceDto> duplicateInstance({required String id}) =>
    RustLib.instance.api.crateApiLauncherDuplicateInstance(id: id);

Future<void> removeInstance({required String id}) =>
    RustLib.instance.api.crateApiLauncherRemoveInstance(id: id);

Future<InstanceDto> installInstance(
        {required String id,
        String? javaPath,
        required bool force,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherInstallInstance(
        id: id, javaPath: javaPath, force: force, onProgress: onProgress);

Future<ProcessDto> launchInstance(
        {required String id,
        required String javaPath,
        String? quickPlaySingleplayer,
        String? quickPlayMultiplayer}) =>
    RustLib.instance.api.crateApiLauncherLaunchInstance(
        id: id,
        javaPath: javaPath,
        quickPlaySingleplayer: quickPlaySingleplayer,
        quickPlayMultiplayer: quickPlayMultiplayer);

/// Java major version required by this instance's Minecraft metadata
/// (`javaVersion.majorVersion`, default 8).
Future<int> getRequiredJavaVersion({required String id}) =>
    RustLib.instance.api.crateApiLauncherGetRequiredJavaVersion(id: id);

Future<void> killInstance({required String id}) =>
    RustLib.instance.api.crateApiLauncherKillInstance(id: id);

Future<List<ProcessDto>> listRunningProcesses() =>
    RustLib.instance.api.crateApiLauncherListRunningProcesses();

/// Subscribe to Minecraft process lifecycle events (`launched` / `finished`).
/// Call once at app start; events are pushed without Dart-side polling.
Future<void> watchProcessEvents(
        {required FutureOr<void> Function(ProcessEventDto) onEvent}) =>
    RustLib.instance.api.crateApiLauncherWatchProcessEvents(onEvent: onEvent);

/// Subscribe to live stdout/stderr log lines (no Dart polling).
Future<void> watchLiveLogEvents(
        {required FutureOr<void> Function(LiveLogEventDto) onEvent}) =>
    RustLib.instance.api.crateApiLauncherWatchLiveLogEvents(onEvent: onEvent);

Future<List<String>> getLiveLogs({required String instanceId}) =>
    RustLib.instance.api.crateApiLauncherGetLiveLogs(instanceId: instanceId);

Future<void> clearLiveLogs({required String instanceId}) =>
    RustLib.instance.api.crateApiLauncherClearLiveLogs(instanceId: instanceId);

Future<String> getLauncherLog({required String instanceId}) =>
    RustLib.instance.api.crateApiLauncherGetLauncherLog(instanceId: instanceId);

Future<List<ModFileDto>> listInstanceMods({required String instanceId}) =>
    RustLib.instance.api
        .crateApiLauncherListInstanceMods(instanceId: instanceId);

/// Background sync: hash unmatched files, resolve Modrinth metadata/authors.
/// Set `checkUpdates` to also query Modrinth for newer versions (slower).
Future<void> syncInstanceContentMetadata(
        {required String instanceId, required bool checkUpdates}) =>
    RustLib.instance.api.crateApiLauncherSyncInstanceContentMetadata(
        instanceId: instanceId, checkUpdates: checkUpdates);

Future<void> setModEnabled(
        {required String instanceId,
        required String relativePath,
        required bool enabled}) =>
    RustLib.instance.api.crateApiLauncherSetModEnabled(
        instanceId: instanceId, relativePath: relativePath, enabled: enabled);

Future<void> removeInstanceMod(
        {required String instanceId, required String relativePath}) =>
    RustLib.instance.api.crateApiLauncherRemoveInstanceMod(
        instanceId: instanceId, relativePath: relativePath);

Future<String> openInstanceFolder({required String instanceId}) =>
    RustLib.instance.api
        .crateApiLauncherOpenInstanceFolder(instanceId: instanceId);

Future<List<WorldDto>> listInstanceWorlds({required String instanceId}) =>
    RustLib.instance.api
        .crateApiLauncherListInstanceWorlds(instanceId: instanceId);

Future<void> deleteInstanceWorld(
        {required String instanceId, required String folder}) =>
    RustLib.instance.api.crateApiLauncherDeleteInstanceWorld(
        instanceId: instanceId, folder: folder);

Future<int> addInstanceServer(
        {required String instanceId,
        required String name,
        required String address}) =>
    RustLib.instance.api.crateApiLauncherAddInstanceServer(
        instanceId: instanceId, name: name, address: address);

Future<void> removeInstanceServer(
        {required String instanceId, required int index}) =>
    RustLib.instance.api.crateApiLauncherRemoveInstanceServer(
        instanceId: instanceId, index: index);

Future<void> editInstanceServer(
        {required String instanceId,
        required int index,
        required String name,
        required String address}) =>
    RustLib.instance.api.crateApiLauncherEditInstanceServer(
        instanceId: instanceId, index: index, name: name, address: address);

/// Server List Ping. Prefer modern protocol; pass `legacy: true` as fallback.
Future<ServerStatusDto> getServerStatus(
        {required String address, int? protocolVersion, bool? legacy}) =>
    RustLib.instance.api.crateApiLauncherGetServerStatus(
        address: address, protocolVersion: protocolVersion, legacy: legacy);

Future<WorldBackupDto> backupInstanceWorld(
        {required String instanceId,
        required String folder,
        required String kind,
        required String compression}) =>
    RustLib.instance.api.crateApiLauncherBackupInstanceWorld(
        instanceId: instanceId,
        folder: folder,
        kind: kind,
        compression: compression);

Future<List<WorldBackupDto>> listWorldBackups(
        {required String instanceId, required String folder}) =>
    RustLib.instance.api.crateApiLauncherListWorldBackups(
        instanceId: instanceId, folder: folder);

Future<void> restoreWorldBackup(
        {required String instanceId, required String backupPath}) =>
    RustLib.instance.api.crateApiLauncherRestoreWorldBackup(
        instanceId: instanceId, backupPath: backupPath);

Future<void> deleteWorldBackup(
        {required String instanceId, required String backupPath}) =>
    RustLib.instance.api.crateApiLauncherDeleteWorldBackup(
        instanceId: instanceId, backupPath: backupPath);

Future<InstanceDto> setInstanceAutoBackupWorlds(
        {required String id, required bool enabled}) =>
    RustLib.instance.api
        .crateApiLauncherSetInstanceAutoBackupWorlds(id: id, enabled: enabled);

/// Stream a 2D overview one completed Minecraft chunk at a time.
Future<void> streamWorldMapPreview(
        {required String instanceId,
        required String folder,
        required FutureOr<bool> Function(WorldMapStreamEventDto) onEvent}) =>
    RustLib.instance.api.crateApiLauncherStreamWorldMapPreview(
        instanceId: instanceId, folder: folder, onEvent: onEvent);

Future<List<GameVersionDto>> listMinecraftVersions() =>
    RustLib.instance.api.crateApiLauncherListMinecraftVersions();

Future<List<LoaderVersionDto>> listLoaderVersions(
        {required String loader, required String gameVersion}) =>
    RustLib.instance.api.crateApiLauncherListLoaderVersions(
        loader: loader, gameVersion: gameVersion);

Future<List<AccountDto>> listAccounts() =>
    RustLib.instance.api.crateApiLauncherListAccounts();

Future<AccountDto> createOfflineAccount({required String username}) =>
    RustLib.instance.api
        .crateApiLauncherCreateOfflineAccount(username: username);

Future<void> setActiveAccount({required String id}) =>
    RustLib.instance.api.crateApiLauncherSetActiveAccount(id: id);

Future<void> removeAccount({required String id}) =>
    RustLib.instance.api.crateApiLauncherRemoveAccount(id: id);

Future<DeviceCodeLoginBeginDto> beginDeviceCodeLogin() =>
    RustLib.instance.api.crateApiLauncherBeginDeviceCodeLogin();

Future<DeviceCodePollResultDto> pollDeviceCode({required String loginId}) =>
    RustLib.instance.api.crateApiLauncherPollDeviceCode(loginId: loginId);

Future<List<YggdrasilServiceDto>> listYggdrasilServices() =>
    RustLib.instance.api.crateApiLauncherListYggdrasilServices();

Future<YggdrasilServiceDto> saveYggdrasilService(
        {String? id, required String name, required String apiUrl}) =>
    RustLib.instance.api.crateApiLauncherSaveYggdrasilService(
        id: id, name: name, apiUrl: apiUrl);

Future<void> removeYggdrasilService({required String id}) =>
    RustLib.instance.api.crateApiLauncherRemoveYggdrasilService(id: id);

Future<YggdrasilLoginBeginDto> beginYggdrasilLogin(
        {required String serviceId,
        required String username,
        required String password}) =>
    RustLib.instance.api.crateApiLauncherBeginYggdrasilLogin(
        serviceId: serviceId, username: username, password: password);

Future<AccountDto> finishYggdrasilLogin(
        {required String loginId, required String profileId}) =>
    RustLib.instance.api.crateApiLauncherFinishYggdrasilLogin(
        loginId: loginId, profileId: profileId);

Future<List<SkinDto>> listAvailableSkins() =>
    RustLib.instance.api.crateApiLauncherListAvailableSkins();

Future<List<CapeDto>> listAvailableCapes() =>
    RustLib.instance.api.crateApiLauncherListAvailableCapes();

Future<Uint8List> normalizeSkinBytes({required List<int> pngBytes}) =>
    RustLib.instance.api.crateApiLauncherNormalizeSkinBytes(pngBytes: pngBytes);

Future<String> detectSkinVariant({required List<int> pngBytes}) =>
    RustLib.instance.api.crateApiLauncherDetectSkinVariant(pngBytes: pngBytes);

Future<SkinDto> saveCustomSkin(
        {required List<int> pngBytes,
        String? name,
        required String variant,
        String? capeId}) =>
    RustLib.instance.api.crateApiLauncherSaveCustomSkin(
        pngBytes: pngBytes, name: name, variant: variant, capeId: capeId);

Future<void> removeCustomSkin({required String textureKey}) =>
    RustLib.instance.api
        .crateApiLauncherRemoveCustomSkin(textureKey: textureKey);

Future<void> equipSkin(
        {required String textureKey,
        required String variant,
        String? capeId,
        String? textureDataUrl}) =>
    RustLib.instance.api.crateApiLauncherEquipSkin(
        textureKey: textureKey,
        variant: variant,
        capeId: capeId,
        textureDataUrl: textureDataUrl);

Future<Uint8List> bakeSkinPreview(
        {required String textureDataUrl,
        required String variant,
        required int scale}) =>
    RustLib.instance.api.crateApiLauncherBakeSkinPreview(
        textureDataUrl: textureDataUrl, variant: variant, scale: scale);

Future<String> installModrinthVersion(
        {required String instanceId,
        required String versionId,
        String? projectType,
        bool? installDeps,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherInstallModrinthVersion(
        instanceId: instanceId,
        versionId: versionId,
        projectType: projectType,
        installDeps: installDeps,
        onProgress: onProgress);

Future<String> installCurseforgeFile(
        {required String instanceId,
        required BigInt modId,
        required BigInt fileId,
        String? projectType,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherInstallCurseforgeFile(
        instanceId: instanceId,
        modId: modId,
        fileId: fileId,
        projectType: projectType,
        onProgress: onProgress);

Future<String> retryMissingContent(
        {required String instanceId,
        required String relativePath,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherRetryMissingContent(
        instanceId: instanceId,
        relativePath: relativePath,
        onProgress: onProgress);

Future<void> installMrpack(
        {required String instanceId,
        required String mrpackPath,
        String? javaPath,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherInstallMrpack(
        instanceId: instanceId,
        mrpackPath: mrpackPath,
        javaPath: javaPath,
        onProgress: onProgress);

Future<InstanceDto> createInstanceFromModrinthModpack(
        {required String versionId,
        String? name,
        String? javaPath,
        String? resumeInstanceId,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherCreateInstanceFromModrinthModpack(
        versionId: versionId,
        name: name,
        javaPath: javaPath,
        resumeInstanceId: resumeInstanceId,
        onProgress: onProgress);

Future<InstanceDto> createInstanceFromCurseforgeModpack(
        {required BigInt modId,
        required BigInt fileId,
        String? name,
        String? javaPath,
        String? resumeInstanceId,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherCreateInstanceFromCurseforgeModpack(
        modId: modId,
        fileId: fileId,
        name: name,
        javaPath: javaPath,
        resumeInstanceId: resumeInstanceId,
        onProgress: onProgress);

Future<AssetPreviewCatalogDto> scanInstanceAssets(
        {required String instanceId, required bool force}) =>
    RustLib.instance.api.crateApiLauncherScanInstanceAssets(
        instanceId: instanceId, force: force);

Future<ResolvedAssetPreviewDto> resolveAssetPreview(
        {required String instanceId, required String entryId}) =>
    RustLib.instance.api.crateApiLauncherResolveAssetPreview(
        instanceId: instanceId, entryId: entryId);

Future<String> detectPackFormat({required String path}) =>
    RustLib.instance.api.crateApiLauncherDetectPackFormat(path: path);

Future<PackImportPreviewDto> previewPackFile({required String path}) =>
    RustLib.instance.api.crateApiLauncherPreviewPackFile(path: path);

Future<PackExportPreviewDto> previewInstanceExport(
        {required String instanceId}) =>
    RustLib.instance.api
        .crateApiLauncherPreviewInstanceExport(instanceId: instanceId);

Future<InstanceDto> createInstanceFromPackFile(
        {required String path,
        String? name,
        String? javaPath,
        String? resumeInstanceId,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherCreateInstanceFromPackFile(
        path: path,
        name: name,
        javaPath: javaPath,
        resumeInstanceId: resumeInstanceId,
        onProgress: onProgress);

Future<InstanceDto> createInstanceFromMmcFolder(
        {required String folder,
        String? name,
        String? javaPath,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherCreateInstanceFromMmcFolder(
        folder: folder, name: name, javaPath: javaPath, onProgress: onProgress);

Future<void> exportInstanceMrpack(
        {required String instanceId,
        required String exportPath,
        String? packName,
        String? versionId,
        String? description,
        List<String>? includeIds,
        List<String>? includePaths,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherExportInstanceMrpack(
        instanceId: instanceId,
        exportPath: exportPath,
        packName: packName,
        versionId: versionId,
        description: description,
        includeIds: includeIds,
        includePaths: includePaths,
        onProgress: onProgress);

/// Export an instance pack. `format`: `mrpack` | `multimc` | `mcbbs`.
///
/// `include_ids` accepts category ids: mods / resourcepacks / shaderpacks /
/// datapacks / config / options / saves. Empty/None → defaults (no saves).
/// `include_paths` optionally restricts to specific relative file paths.
Future<void> exportInstancePack(
        {required String instanceId,
        required String exportPath,
        required String format,
        String? packName,
        String? versionId,
        String? description,
        List<String>? includeIds,
        List<String>? includePaths,
        required FutureOr<void> Function(double, String) onProgress}) =>
    RustLib.instance.api.crateApiLauncherExportInstancePack(
        instanceId: instanceId,
        exportPath: exportPath,
        format: format,
        packName: packName,
        versionId: versionId,
        description: description,
        includeIds: includeIds,
        includePaths: includePaths,
        onProgress: onProgress);

/// Create a desktop shortcut that launches AML with an `aml://launch/…` argument.
///
/// On Windows this writes a `.lnk` pointing at the current executable.
/// `server_address` and `world_folder` are mutually exclusive.
///
/// `icon` may be a local image path or a `data:image/...;base64,…` URL. When omitted,
/// server shortcuts prefer the `servers.dat` favicon, otherwise the instance icon.
Future<String> createDesktopShortcut(
        {required String displayName,
        required String outputPath,
        required String instanceId,
        String? serverAddress,
        String? worldFolder,
        String? icon}) =>
    RustLib.instance.api.crateApiLauncherCreateDesktopShortcut(
        displayName: displayName,
        outputPath: outputPath,
        instanceId: instanceId,
        serverAddress: serverAddress,
        worldFolder: worldFolder,
        icon: icon);

class AccountDto {
  final String id;
  final String kind;
  final String username;
  final String uuid;
  final String? authServerId;
  final bool active;

  const AccountDto({
    required this.id,
    required this.kind,
    required this.username,
    required this.uuid,
    this.authServerId,
    required this.active,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      username.hashCode ^
      uuid.hashCode ^
      authServerId.hashCode ^
      active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          username == other.username &&
          uuid == other.uuid &&
          authServerId == other.authServerId &&
          active == other.active;
}

class AssetPreviewCatalogDto {
  final String fingerprint;
  final String scannedAt;
  final List<AssetPreviewEntryDto> entries;

  const AssetPreviewCatalogDto({
    required this.fingerprint,
    required this.scannedAt,
    required this.entries,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^ scannedAt.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetPreviewCatalogDto &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          scannedAt == other.scannedAt &&
          entries == other.entries;
}

class AssetPreviewEntryDto {
  final String id;
  final String namespace;
  final String name;
  final String category;
  final String? modelPath;
  final String? texturePath;
  final String sourceId;
  final String sourceLabel;
  final String sourceKind;

  const AssetPreviewEntryDto({
    required this.id,
    required this.namespace,
    required this.name,
    required this.category,
    this.modelPath,
    this.texturePath,
    required this.sourceId,
    required this.sourceLabel,
    required this.sourceKind,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      namespace.hashCode ^
      name.hashCode ^
      category.hashCode ^
      modelPath.hashCode ^
      texturePath.hashCode ^
      sourceId.hashCode ^
      sourceLabel.hashCode ^
      sourceKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetPreviewEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          namespace == other.namespace &&
          name == other.name &&
          category == other.category &&
          modelPath == other.modelPath &&
          texturePath == other.texturePath &&
          sourceId == other.sourceId &&
          sourceLabel == other.sourceLabel &&
          sourceKind == other.sourceKind;
}

class CapeDto {
  final String id;
  final String name;
  final String textureDataUrl;
  final bool isEquipped;

  const CapeDto({
    required this.id,
    required this.name,
    required this.textureDataUrl,
    required this.isEquipped,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      textureDataUrl.hashCode ^
      isEquipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CapeDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          textureDataUrl == other.textureDataUrl &&
          isEquipped == other.isEquipped;
}

class DeviceCodeLoginBeginDto {
  final String loginId;
  final String userCode;
  final String verificationUri;
  final BigInt interval;
  final BigInt expiresIn;
  final String message;

  const DeviceCodeLoginBeginDto({
    required this.loginId,
    required this.userCode,
    required this.verificationUri,
    required this.interval,
    required this.expiresIn,
    required this.message,
  });

  @override
  int get hashCode =>
      loginId.hashCode ^
      userCode.hashCode ^
      verificationUri.hashCode ^
      interval.hashCode ^
      expiresIn.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodeLoginBeginDto &&
          runtimeType == other.runtimeType &&
          loginId == other.loginId &&
          userCode == other.userCode &&
          verificationUri == other.verificationUri &&
          interval == other.interval &&
          expiresIn == other.expiresIn &&
          message == other.message;
}

class DeviceCodePollResultDto {
  /// "pending" | "success" | "expired" | "declined" | "slow_down"
  final String status;

  /// Only present when status == "success".
  final AccountDto? account;

  /// Human-readable error for unexpected failures.
  final String? error;

  const DeviceCodePollResultDto({
    required this.status,
    this.account,
    this.error,
  });

  @override
  int get hashCode => status.hashCode ^ account.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodePollResultDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          account == other.account &&
          error == other.error;
}

class GameVersionDto {
  final String id;
  final String type;
  final String releaseTime;

  const GameVersionDto({
    required this.id,
    required this.type,
    required this.releaseTime,
  });

  @override
  int get hashCode => id.hashCode ^ type.hashCode ^ releaseTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameVersionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          releaseTime == other.releaseTime;
}

class InstanceDto {
  final String id;
  final String path;
  final String name;
  final String gameVersion;
  final String loader;
  final String? loaderVersion;
  final String installStage;
  final String? javaPath;
  final PlatformInt64? memoryMb;
  final String? extraJvmArgs;
  final PlatformInt64? windowWidth;
  final PlatformInt64? windowHeight;
  final bool? fullscreen;
  final String? environmentVars;
  final String? preLaunchCommand;
  final String? wrapperCommand;
  final String? postExitCommand;
  final String updateChannel;
  final bool autoBackupWorlds;
  final List<String> groups;
  final String? modpackProjectId;
  final String? modpackVersionId;
  final String? modpackVersionNumber;
  final String? modpackSource;
  final String? modpackTitle;
  final String? icon;
  final String? lastPlayed;
  final String createdAt;

  const InstanceDto({
    required this.id,
    required this.path,
    required this.name,
    required this.gameVersion,
    required this.loader,
    this.loaderVersion,
    required this.installStage,
    this.javaPath,
    this.memoryMb,
    this.extraJvmArgs,
    this.windowWidth,
    this.windowHeight,
    this.fullscreen,
    this.environmentVars,
    this.preLaunchCommand,
    this.wrapperCommand,
    this.postExitCommand,
    required this.updateChannel,
    required this.autoBackupWorlds,
    required this.groups,
    this.modpackProjectId,
    this.modpackVersionId,
    this.modpackVersionNumber,
    this.modpackSource,
    this.modpackTitle,
    this.icon,
    this.lastPlayed,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      name.hashCode ^
      gameVersion.hashCode ^
      loader.hashCode ^
      loaderVersion.hashCode ^
      installStage.hashCode ^
      javaPath.hashCode ^
      memoryMb.hashCode ^
      extraJvmArgs.hashCode ^
      windowWidth.hashCode ^
      windowHeight.hashCode ^
      fullscreen.hashCode ^
      environmentVars.hashCode ^
      preLaunchCommand.hashCode ^
      wrapperCommand.hashCode ^
      postExitCommand.hashCode ^
      updateChannel.hashCode ^
      autoBackupWorlds.hashCode ^
      groups.hashCode ^
      modpackProjectId.hashCode ^
      modpackVersionId.hashCode ^
      modpackVersionNumber.hashCode ^
      modpackSource.hashCode ^
      modpackTitle.hashCode ^
      icon.hashCode ^
      lastPlayed.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstanceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          name == other.name &&
          gameVersion == other.gameVersion &&
          loader == other.loader &&
          loaderVersion == other.loaderVersion &&
          installStage == other.installStage &&
          javaPath == other.javaPath &&
          memoryMb == other.memoryMb &&
          extraJvmArgs == other.extraJvmArgs &&
          windowWidth == other.windowWidth &&
          windowHeight == other.windowHeight &&
          fullscreen == other.fullscreen &&
          environmentVars == other.environmentVars &&
          preLaunchCommand == other.preLaunchCommand &&
          wrapperCommand == other.wrapperCommand &&
          postExitCommand == other.postExitCommand &&
          updateChannel == other.updateChannel &&
          autoBackupWorlds == other.autoBackupWorlds &&
          groups == other.groups &&
          modpackProjectId == other.modpackProjectId &&
          modpackVersionId == other.modpackVersionId &&
          modpackVersionNumber == other.modpackVersionNumber &&
          modpackSource == other.modpackSource &&
          modpackTitle == other.modpackTitle &&
          icon == other.icon &&
          lastPlayed == other.lastPlayed &&
          createdAt == other.createdAt;
}

class LaunchDefaultsDto {
  final PlatformInt64 memoryMb;
  final String? extraJvmArgs;
  final PlatformInt64 windowWidth;
  final PlatformInt64 windowHeight;
  final bool fullscreen;
  final String? environmentVars;
  final String? preLaunchCommand;
  final String? wrapperCommand;
  final String? postExitCommand;
  final String? gameLanguage;

  const LaunchDefaultsDto({
    required this.memoryMb,
    this.extraJvmArgs,
    required this.windowWidth,
    required this.windowHeight,
    required this.fullscreen,
    this.environmentVars,
    this.preLaunchCommand,
    this.wrapperCommand,
    this.postExitCommand,
    this.gameLanguage,
  });

  @override
  int get hashCode =>
      memoryMb.hashCode ^
      extraJvmArgs.hashCode ^
      windowWidth.hashCode ^
      windowHeight.hashCode ^
      fullscreen.hashCode ^
      environmentVars.hashCode ^
      preLaunchCommand.hashCode ^
      wrapperCommand.hashCode ^
      postExitCommand.hashCode ^
      gameLanguage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaunchDefaultsDto &&
          runtimeType == other.runtimeType &&
          memoryMb == other.memoryMb &&
          extraJvmArgs == other.extraJvmArgs &&
          windowWidth == other.windowWidth &&
          windowHeight == other.windowHeight &&
          fullscreen == other.fullscreen &&
          environmentVars == other.environmentVars &&
          preLaunchCommand == other.preLaunchCommand &&
          wrapperCommand == other.wrapperCommand &&
          postExitCommand == other.postExitCommand &&
          gameLanguage == other.gameLanguage;
}

class LiveLogEventDto {
  final String instanceId;

  /// One line or a newline-delimited batch.
  final String line;

  /// When true, the live buffer was cleared (e.g. new launch).
  final bool cleared;

  const LiveLogEventDto({
    required this.instanceId,
    required this.line,
    required this.cleared,
  });

  @override
  int get hashCode => instanceId.hashCode ^ line.hashCode ^ cleared.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveLogEventDto &&
          runtimeType == other.runtimeType &&
          instanceId == other.instanceId &&
          line == other.line &&
          cleared == other.cleared;
}

class LoaderVersionDto {
  final String id;
  final bool stable;

  const LoaderVersionDto({
    required this.id,
    required this.stable,
  });

  @override
  int get hashCode => id.hashCode ^ stable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoaderVersionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          stable == other.stable;
}

class ModFileDto {
  final String name;
  final String relativePath;
  final bool enabled;
  final BigInt sizeBytes;
  final String projectType;
  final String? projectId;
  final String? versionId;
  final String? versionNumber;
  final String? versionName;
  final String? projectTitle;
  final String? projectIconUrl;
  final String? author;
  final String? authorAvatarUrl;
  final String? authorId;
  final String? authorType;
  final String? updateVersionId;
  final bool hasUpdate;
  final bool isMissing;

  const ModFileDto({
    required this.name,
    required this.relativePath,
    required this.enabled,
    required this.sizeBytes,
    required this.projectType,
    this.projectId,
    this.versionId,
    this.versionNumber,
    this.versionName,
    this.projectTitle,
    this.projectIconUrl,
    this.author,
    this.authorAvatarUrl,
    this.authorId,
    this.authorType,
    this.updateVersionId,
    required this.hasUpdate,
    required this.isMissing,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      relativePath.hashCode ^
      enabled.hashCode ^
      sizeBytes.hashCode ^
      projectType.hashCode ^
      projectId.hashCode ^
      versionId.hashCode ^
      versionNumber.hashCode ^
      versionName.hashCode ^
      projectTitle.hashCode ^
      projectIconUrl.hashCode ^
      author.hashCode ^
      authorAvatarUrl.hashCode ^
      authorId.hashCode ^
      authorType.hashCode ^
      updateVersionId.hashCode ^
      hasUpdate.hashCode ^
      isMissing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModFileDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          relativePath == other.relativePath &&
          enabled == other.enabled &&
          sizeBytes == other.sizeBytes &&
          projectType == other.projectType &&
          projectId == other.projectId &&
          versionId == other.versionId &&
          versionNumber == other.versionNumber &&
          versionName == other.versionName &&
          projectTitle == other.projectTitle &&
          projectIconUrl == other.projectIconUrl &&
          author == other.author &&
          authorAvatarUrl == other.authorAvatarUrl &&
          authorId == other.authorId &&
          authorType == other.authorType &&
          updateVersionId == other.updateVersionId &&
          hasUpdate == other.hasUpdate &&
          isMissing == other.isMissing;
}

class ModelElementDto {
  final double fromX;
  final double fromY;
  final double fromZ;
  final double toX;
  final double toY;
  final double toZ;
  final ModelFaceDto? north;
  final ModelFaceDto? south;
  final ModelFaceDto? east;
  final ModelFaceDto? west;
  final ModelFaceDto? up;
  final ModelFaceDto? down;

  const ModelElementDto({
    required this.fromX,
    required this.fromY,
    required this.fromZ,
    required this.toX,
    required this.toY,
    required this.toZ,
    this.north,
    this.south,
    this.east,
    this.west,
    this.up,
    this.down,
  });

  @override
  int get hashCode =>
      fromX.hashCode ^
      fromY.hashCode ^
      fromZ.hashCode ^
      toX.hashCode ^
      toY.hashCode ^
      toZ.hashCode ^
      north.hashCode ^
      south.hashCode ^
      east.hashCode ^
      west.hashCode ^
      up.hashCode ^
      down.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelElementDto &&
          runtimeType == other.runtimeType &&
          fromX == other.fromX &&
          fromY == other.fromY &&
          fromZ == other.fromZ &&
          toX == other.toX &&
          toY == other.toY &&
          toZ == other.toZ &&
          north == other.north &&
          south == other.south &&
          east == other.east &&
          west == other.west &&
          up == other.up &&
          down == other.down;
}

class ModelFaceDto {
  final int textureIndex;
  final double u0;
  final double v0;
  final double u1;
  final double v1;

  const ModelFaceDto({
    required this.textureIndex,
    required this.u0,
    required this.v0,
    required this.u1,
    required this.v1,
  });

  @override
  int get hashCode =>
      textureIndex.hashCode ^
      u0.hashCode ^
      v0.hashCode ^
      u1.hashCode ^
      v1.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelFaceDto &&
          runtimeType == other.runtimeType &&
          textureIndex == other.textureIndex &&
          u0 == other.u0 &&
          v0 == other.v0 &&
          u1 == other.u1 &&
          v1 == other.v1;
}

class PackContentCategoryDto {
  final String id;
  final String label;
  final int fileCount;
  final BigInt totalBytes;
  final List<PackContentFileDto> files;

  const PackContentCategoryDto({
    required this.id,
    required this.label,
    required this.fileCount,
    required this.totalBytes,
    required this.files,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      fileCount.hashCode ^
      totalBytes.hashCode ^
      files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackContentCategoryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          fileCount == other.fileCount &&
          totalBytes == other.totalBytes &&
          files == other.files;
}

class PackContentFileDto {
  final String path;
  final String name;
  final BigInt sizeBytes;
  final String? iconUrl;
  final String? title;

  const PackContentFileDto({
    required this.path,
    required this.name,
    required this.sizeBytes,
    this.iconUrl,
    this.title,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      sizeBytes.hashCode ^
      iconUrl.hashCode ^
      title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackContentFileDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          sizeBytes == other.sizeBytes &&
          iconUrl == other.iconUrl &&
          title == other.title;
}

class PackExportPreviewDto {
  final String name;
  final String gameVersion;
  final String loader;
  final List<PackContentCategoryDto> categories;

  const PackExportPreviewDto({
    required this.name,
    required this.gameVersion,
    required this.loader,
    required this.categories,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      gameVersion.hashCode ^
      loader.hashCode ^
      categories.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackExportPreviewDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          gameVersion == other.gameVersion &&
          loader == other.loader &&
          categories == other.categories;
}

class PackImportPreviewDto {
  final String kind;
  final String kindLabel;
  final String name;
  final String? version;
  final String? gameVersion;
  final String? loader;
  final List<PackContentCategoryDto> categories;
  final bool hasCover;
  final Uint8List? coverPng;

  const PackImportPreviewDto({
    required this.kind,
    required this.kindLabel,
    required this.name,
    this.version,
    this.gameVersion,
    this.loader,
    required this.categories,
    required this.hasCover,
    this.coverPng,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      kindLabel.hashCode ^
      name.hashCode ^
      version.hashCode ^
      gameVersion.hashCode ^
      loader.hashCode ^
      categories.hashCode ^
      hasCover.hashCode ^
      coverPng.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackImportPreviewDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          kindLabel == other.kindLabel &&
          name == other.name &&
          version == other.version &&
          gameVersion == other.gameVersion &&
          loader == other.loader &&
          categories == other.categories &&
          hasCover == other.hasCover &&
          coverPng == other.coverPng;
}

class ProcessDto {
  final String uuid;
  final String instanceId;

  /// Android only: path of the private launch manifest; Dart passes it to
  /// `GameActivity` through a platform channel. `None` on desktop.
  final String? manifestPath;

  const ProcessDto({
    required this.uuid,
    required this.instanceId,
    this.manifestPath,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^ instanceId.hashCode ^ manifestPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          instanceId == other.instanceId &&
          manifestPath == other.manifestPath;
}

class ProcessEventDto {
  final String instanceId;
  final String uuid;

  /// `"launched"` | `"finished"`
  final String event;
  final String message;

  const ProcessEventDto({
    required this.instanceId,
    required this.uuid,
    required this.event,
    required this.message,
  });

  @override
  int get hashCode =>
      instanceId.hashCode ^ uuid.hashCode ^ event.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessEventDto &&
          runtimeType == other.runtimeType &&
          instanceId == other.instanceId &&
          uuid == other.uuid &&
          event == other.event &&
          message == other.message;
}

class ResolvedAssetPreviewDto {
  final String entryId;
  final String previewKind;
  final List<ModelElementDto> elements;
  final List<Uint8List> textures;
  final double? guiRotationX;
  final double? guiRotationY;
  final double? guiRotationZ;
  final double? guiScale;

  const ResolvedAssetPreviewDto({
    required this.entryId,
    required this.previewKind,
    required this.elements,
    required this.textures,
    this.guiRotationX,
    this.guiRotationY,
    this.guiRotationZ,
    this.guiScale,
  });

  @override
  int get hashCode =>
      entryId.hashCode ^
      previewKind.hashCode ^
      elements.hashCode ^
      textures.hashCode ^
      guiRotationX.hashCode ^
      guiRotationY.hashCode ^
      guiRotationZ.hashCode ^
      guiScale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolvedAssetPreviewDto &&
          runtimeType == other.runtimeType &&
          entryId == other.entryId &&
          previewKind == other.previewKind &&
          elements == other.elements &&
          textures == other.textures &&
          guiRotationX == other.guiRotationX &&
          guiRotationY == other.guiRotationY &&
          guiRotationZ == other.guiRotationZ &&
          guiScale == other.guiScale;
}

class ServerStatusDto {
  /// Raw MOTD JSON (string or chat component). UI parses colors / formatting.
  final String? descriptionJson;
  final int? playersOnline;
  final int? playersMax;
  final List<String> playerSample;
  final String? versionName;
  final int? versionProtocol;
  final bool legacy;

  /// `data:image/png;base64,...` when present.
  final String? favicon;
  final PlatformInt64? pingMs;

  const ServerStatusDto({
    this.descriptionJson,
    this.playersOnline,
    this.playersMax,
    required this.playerSample,
    this.versionName,
    this.versionProtocol,
    required this.legacy,
    this.favicon,
    this.pingMs,
  });

  @override
  int get hashCode =>
      descriptionJson.hashCode ^
      playersOnline.hashCode ^
      playersMax.hashCode ^
      playerSample.hashCode ^
      versionName.hashCode ^
      versionProtocol.hashCode ^
      legacy.hashCode ^
      favicon.hashCode ^
      pingMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerStatusDto &&
          runtimeType == other.runtimeType &&
          descriptionJson == other.descriptionJson &&
          playersOnline == other.playersOnline &&
          playersMax == other.playersMax &&
          playerSample == other.playerSample &&
          versionName == other.versionName &&
          versionProtocol == other.versionProtocol &&
          legacy == other.legacy &&
          favicon == other.favicon &&
          pingMs == other.pingMs;
}

class SkinDto {
  final String textureKey;
  final String? name;
  final String? section;
  final String variant;
  final String? capeId;
  final String textureDataUrl;
  final String source;
  final bool isEquipped;

  const SkinDto({
    required this.textureKey,
    this.name,
    this.section,
    required this.variant,
    this.capeId,
    required this.textureDataUrl,
    required this.source,
    required this.isEquipped,
  });

  @override
  int get hashCode =>
      textureKey.hashCode ^
      name.hashCode ^
      section.hashCode ^
      variant.hashCode ^
      capeId.hashCode ^
      textureDataUrl.hashCode ^
      source.hashCode ^
      isEquipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkinDto &&
          runtimeType == other.runtimeType &&
          textureKey == other.textureKey &&
          name == other.name &&
          section == other.section &&
          variant == other.variant &&
          capeId == other.capeId &&
          textureDataUrl == other.textureDataUrl &&
          source == other.source &&
          isEquipped == other.isEquipped;
}

class WorldBackupDto {
  final String id;
  final String worldFolder;
  final String fileName;
  final String createdAt;
  final BigInt sizeBytes;
  final String path;
  final bool auto;

  /// `full` | `incremental`
  final String kind;

  /// `store` | `fast` | `balanced` | `max`
  final String compression;
  final String? parentId;
  final String? baseFullId;
  final String? iconPath;
  final int fileCount;

  const WorldBackupDto({
    required this.id,
    required this.worldFolder,
    required this.fileName,
    required this.createdAt,
    required this.sizeBytes,
    required this.path,
    required this.auto,
    required this.kind,
    required this.compression,
    this.parentId,
    this.baseFullId,
    this.iconPath,
    required this.fileCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      worldFolder.hashCode ^
      fileName.hashCode ^
      createdAt.hashCode ^
      sizeBytes.hashCode ^
      path.hashCode ^
      auto.hashCode ^
      kind.hashCode ^
      compression.hashCode ^
      parentId.hashCode ^
      baseFullId.hashCode ^
      iconPath.hashCode ^
      fileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorldBackupDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          worldFolder == other.worldFolder &&
          fileName == other.fileName &&
          createdAt == other.createdAt &&
          sizeBytes == other.sizeBytes &&
          path == other.path &&
          auto == other.auto &&
          kind == other.kind &&
          compression == other.compression &&
          parentId == other.parentId &&
          baseFullId == other.baseFullId &&
          iconPath == other.iconPath &&
          fileCount == other.fileCount;
}

class WorldDto {
  final String kind;
  final String name;
  final String folder;
  final String gameMode;
  final bool hardcore;
  final PlatformInt64? lastPlayedMs;
  final String? iconPath;
  final String? iconDataUrl;
  final String? serverAddress;
  final int? serverIndex;
  final int backupCount;

  const WorldDto({
    required this.kind,
    required this.name,
    required this.folder,
    required this.gameMode,
    required this.hardcore,
    this.lastPlayedMs,
    this.iconPath,
    this.iconDataUrl,
    this.serverAddress,
    this.serverIndex,
    required this.backupCount,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      name.hashCode ^
      folder.hashCode ^
      gameMode.hashCode ^
      hardcore.hashCode ^
      lastPlayedMs.hashCode ^
      iconPath.hashCode ^
      iconDataUrl.hashCode ^
      serverAddress.hashCode ^
      serverIndex.hashCode ^
      backupCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorldDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          name == other.name &&
          folder == other.folder &&
          gameMode == other.gameMode &&
          hardcore == other.hardcore &&
          lastPlayedMs == other.lastPlayedMs &&
          iconPath == other.iconPath &&
          iconDataUrl == other.iconDataUrl &&
          serverAddress == other.serverAddress &&
          serverIndex == other.serverIndex &&
          backupCount == other.backupCount;
}

class WorldMapChunkDto {
  final int chunkX;
  final int chunkZ;
  final Uint8List rgba;

  const WorldMapChunkDto({
    required this.chunkX,
    required this.chunkZ,
    required this.rgba,
  });

  @override
  int get hashCode => chunkX.hashCode ^ chunkZ.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorldMapChunkDto &&
          runtimeType == other.runtimeType &&
          chunkX == other.chunkX &&
          chunkZ == other.chunkZ &&
          rgba == other.rgba;
}

class WorldMapStreamEventDto {
  final int minChunkX;
  final int minChunkZ;
  final int maxChunkX;
  final int maxChunkZ;
  final int chunksDone;
  final int chunksTotal;
  final WorldMapChunkDto? chunk;
  final bool done;

  const WorldMapStreamEventDto({
    required this.minChunkX,
    required this.minChunkZ,
    required this.maxChunkX,
    required this.maxChunkZ,
    required this.chunksDone,
    required this.chunksTotal,
    this.chunk,
    required this.done,
  });

  @override
  int get hashCode =>
      minChunkX.hashCode ^
      minChunkZ.hashCode ^
      maxChunkX.hashCode ^
      maxChunkZ.hashCode ^
      chunksDone.hashCode ^
      chunksTotal.hashCode ^
      chunk.hashCode ^
      done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorldMapStreamEventDto &&
          runtimeType == other.runtimeType &&
          minChunkX == other.minChunkX &&
          minChunkZ == other.minChunkZ &&
          maxChunkX == other.maxChunkX &&
          maxChunkZ == other.maxChunkZ &&
          chunksDone == other.chunksDone &&
          chunksTotal == other.chunksTotal &&
          chunk == other.chunk &&
          done == other.done;
}

class YggdrasilLoginBeginDto {
  final String loginId;
  final List<YggdrasilProfileDto> profiles;

  const YggdrasilLoginBeginDto({
    required this.loginId,
    required this.profiles,
  });

  @override
  int get hashCode => loginId.hashCode ^ profiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YggdrasilLoginBeginDto &&
          runtimeType == other.runtimeType &&
          loginId == other.loginId &&
          profiles == other.profiles;
}

class YggdrasilProfileDto {
  final String id;
  final String name;
  final String? skinUrl;

  const YggdrasilProfileDto({
    required this.id,
    required this.name,
    this.skinUrl,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ skinUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YggdrasilProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          skinUrl == other.skinUrl;
}

class YggdrasilServiceDto {
  final String id;
  final String name;
  final String apiUrl;
  final bool builtin;

  const YggdrasilServiceDto({
    required this.id,
    required this.name,
    required this.apiUrl,
    required this.builtin,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ apiUrl.hashCode ^ builtin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YggdrasilServiceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          apiUrl == other.apiUrl &&
          builtin == other.builtin;
}
